### ISSUE TITLE
Opensource maintenance: Overflow

### ISSUE THREAD

**Issue by alxflw** [onflow/developer-grants#12]
# <Project name>

# Grant category
OpenSource maintenance

# Description
Set of go scripts to make it easer to run a story consisting of creating accounts, deploying contracts, executing transactions and running scripts on the Flow Blockchain. These go scripts also make writing integration tests of your smart contracts much easier.

## Problem statement

Flow developers using Go to ...
- tell a story
- run a lot of repetitive tasks
- run integration tests

Need evidenced by usage:
- 4 known projects using it
- 3 contributors
- 13 Github stars

## Proposed solution
A Go library that makes it is to automate tests. Opensource repository available here: https://github.com/bjartek/overflow

## Impact
Other Go developers can automate work and run integration tests. 

# Milestones and funding

Overall duration to deliver future milestones: ~6 months. Total FLOW requested: 28,000.

| Milestone | Deliverables   | Timeline | Risks                   | FLOW requested |
| --------- | -------------- | -------- | ----------------------- | -------------- |
| 0 - Ongoing maintenance and contribution   | - | - | - | 5,000 FLOW           |
| 1 - Support gas estimation   | Add method for gas estimates, update CLI logging (https://github.com/onflow/flow-cli/issues/325) | ~ 4 weeks | Need guidance from CLI engineers to improve logging | 4,000 FLOW           |
| 2 - Consistent and complete API  | Update library interface and add documentation  | ~ 2 weeks | - | 1,500 FLOW           |
| 3 - Increase test coverage (https://github.com/bjartek/overflow/issues/19)   | 90%+ coverage  | ~ 2 weeks | - | 2,000 FLOW           |
| 4 - V3 release  | Prep, release, and announce at the Flow office hours and blog post | ~1 week | - | 500 FLOW           |
| 5 - Adoption  | Get 10+ Flow projects to use Overflow | ~4 weeks | - | 5,000 FLOW           |
| 6 - Maintenance | Help resolve issues developers might face (not including new feature development) |  3 months | - | 10,000 FLOW           |

# Team

| Name | Role                | Bio | Contact         |
| ---- | ------------------- | --- | --------------- |
| Bjarte | Main contributor | - | @bjartek |

# Milestone completion
- [x] Ongoing maintenance and contribution
- [x] Support gas estimation
- [x] Consistent and complete API
- [x] Increase test coverage
- [ ] V3 release
- [x] Adoption
- [x] Maintenance

**Comment by hichana** [comment]
I think this would make a great contribution to the community. Overflow basically saves me from tediously writing my own CLI, which is a huge time/effort saver. I hope we can get more people interested in it.

**Comment by alxflw** [comment]
This grant proposal has been approved 🚀

**Comment by bjartek** [comment]
Thank you <3

**Comment by bjartek** [comment]
# Overflow follow up grant

Almost all the milestones for the initail grant of overflow are done, I will release v1 soon and write a blogpost and hold an AMA about it. 

In order to continue to maintain overflow I am applying for an follow up grant. 

The followings milestones are things that I think would be very nice to have

== Continued supported. 
In the three months since the grant launched I have helped many projects convert code from old overflow syntax to the new one. I have also commited fixes to onflow core contracts to show how the new syntax could improve the readability of the tests. 

I would like to ask for a monthly fee to keep overflow a float. 

The last grant gave out 10k flow (valued at 5 when the grant was given) for a total of 50k USD for 3 months. So 16666 USD per month. Since the initial support period is over I think that sum is a little high so what about 10000 a month.

This will include fixing small issues in the overflow repo that are tagged with small.

== Create memory snapshots and start from them
Flow cli has support for starting the emulator from a file. I would like to create some convenience around that so it is possible to set up a project/run an overflow story and create a memory dump of that. This can be very usfull as a debugging tool. You have an issue? can you create a dump for me?

It could also be used to create a dump of a test setup to enable very quick bootstrap of tests. The .find repo has 30 contracts now and the test overhead to start up a new emulator is seconds not miliseconds as it should be. 

For this feature I would like to ask for 5000 USD
	
== Bootstrap new project and maintain it

When you start up a new project today you often want to get externally defined contracts and set up a bare bones skeleton. I propse to add features to overflow that enable it to be used to bootstrap the backend side of a flow project. 

This includes: 
 - creating a new github repo
 - get common shared code and put into project
 - set up NPM module of interactions (or work with interaction template)
 - diff the state of your local contracts with contracts on mainnet/testnet to see if your external dependencies have changed
 - offer simpler local version of some contracts on mainnet that is hard to use for testing USDC for instance

The end result is a tool that allow anybody that want to start with an NFT project using overflow to do so easy. 


For this feature I would like to ask for 10000 USD

**Comment by bjartek** [comment]
I belive this can be closed.
