### ISSUE TITLE
Proposal for fixing issues in Access/Observer Nodes

### ISSUE THREAD

**Issue by Guitarheroua** [onflow/developer-grants#168]
# <Project name>

# Grant category

- Open-source maintenance

# Description

This grant request aims to fix the informativeness and stability of Access/Observer nodes. It covers 6 open issues that are to address technical debt for Access and Observer nodes that the core Flow team would like to resolve but cannot prioritize.

## Proposed solution

1 - Resolve issue onflow/flow-go#3040:
The [role.go](https://github.com/onflow/flow-go/blob/98f7a791d042f674f56ad483c3cb6b905b1f8a6b/model/flow/role.go) should be extended with a new role "RoleObserver" and used in [observer_builder.go](https://github.com/onflow/flow-go/blob/master/cmd/observer/node_builder/observer_builder.go)

2 - Add API to return the current version of Protocol/Cadence (onflow/flow-go/issues/2134):
Flow already reports info in metrics such as [server, commit, SporkID, and protocol version](https://github.com/onflow/flow-go/blob/master/cmd/scaffold.go#L717). There is no Cadence version, so this, possibly, could be out of scope for this task, as will need extra effort to add it.

3 - [Access Node] Add field to access API responses indicating what the latest block height was on the node ( resolves onflow/flow-go/issues/2906 ):
The most naive approach of querying `state.Final()` on each call can be very costly, as it requires accessing the database. To optimize this process, we suggest adopting an event-driven approach where the finalized block is reported via pub-sub and cached locally. The cached block can then be added to responses, although this method may not be entirely accurate. To implement this change, it would be necessary to update the result types in protobuf. We recommend avoiding any modifications to the backend API and instead adding the finalized height at the GRPC handler level.
Another alternative is to include the finalized height in trailing metadata. However, this solution would only be applicable to GRPC.

4 - [Access] Add integration test for signer indices (onflow/flow-go/issues/3133 )
Write an integration test that spins up AN and performs requests for methods that use
```
Handler.signerIndicesDecoder:
GetLatestBlock
GetBlockByHeight
GetBlockByID
GetLatestBlockHeader
GetBlockHeaderByHeight
GetBlockHeaderByID
```
and confirm that responses contain correct signer IDs against blocks received from consensus followers similar to [this test](https://github.com/onflow/flow-go/blob/master/integration/tests/access/consensus_follower_test.go).

5 - [Access API] Add collection_id and block_id to GetTransactionResult parameters to avoid duplicate transaction hashes (resolves onflow/flow-go/issues/2099 ): 
The access node [api.go GetTransactionResult](https://github.com/onflow/flow-go/blob/98f7a791d042f674f56ad483c3cb6b905b1f8a6b/access/api.go#L31) should be extended with two new _**collection_id**_ and _**block_id**_ `flow.Identifier` parameters. For backward compatibility old functionality will work when collection_id and block_id will be flow.ZeroID. Protobuf GetTransactionRequest type should also be extended with two new fields respectively.
 
6 - [Access] Fix REST API metrics ( resolves onflow/flow-go#3971 )
- enable metrics.
- confirm memory leak with heap profiler, and resolve a memory leak.
- make sure that metrics are correctly collected using localnet and grafana, and fix if needed.
- write an integration test that starts AN, performs a batch of API requests, and validates if metrics were correctly recorded using /metrics endpoint.

## Impact

Proposed fixes will improve the informativeness and stability of Access/Observer nodes.

# Milestones and funding

> Note: Please consider adoption and/or maintenance milestones at the end of your project.

| Milestone | Deliverables   | Timeline | Risks                   | USD proposal |
| --------- | -------------- | -------- | ----------------------- | -------------- |
|  1 - Observer node logs as node role access  | Fixes: [onflow/flow-go#3040](https://github.com/onflow/flow-go/issues/3040) | 4h | - | 200$ |
| 2 - Add API to return the current version of Protocol/Cadence  | Fixes: [onflow/flow-go#2134](https://github.com/onflow/flow-go/issues/2134) | 16h | - | 800$ |
| 3 - [Access Node] Add field to access API responses indicating what the latest block height was on the node | Fixes: [onflow/flow-go#2906](https://github.com/onflow/flow-go/issues/2906) | 16h | - | 800$ |
| 4 - [Access] Add integration test for signer indices | Fixes: [onflow/flow-go#3133](https://github.com/onflow/flow-go/issues/3133) | 24h | - | 1200$ |
| 5 - [Access API] Add collection_id and block_id to GetTransactionResult parameters to avoid duplicate transaction hashes | Fixes: [onflow/flow-go#2099](https://github.com/onflow/flow-go/issues/2099) | 32h | - | 1600$ |
| 6 - [Access] Fix REST API metrics | Fixes: [onflow/flow-go#3971](https://github.com/onflow/flow-go/issues/3971) | 40h | - | 2000$ |

Total funding proposed: 6600 USD
  
# Team

| Name | Role                | Bio | Contact         |
| ---- | ------------------- | --- | --------------- |
| Andrii | Senior Blockchain Engineer | Software Engineer with over 8 years of technical experience.<br />Primary skills include C++(Standards 11,14,17), Rust, and Golang.<br />I have been highly focused on blockchain development for the last few years. Here are a few examples of my projects that could be interesting when applying for this grant: <br />- `2016-2019`: Supply chain planning and management tools/applications for huge manufacturers and logistic businesses. Worked in a team of 20+ engineers. Gained experience in Golang. Build integrations between applications using REST API. <br />- `2021-2022`: Complex DeFi lending/borrowing system using Rust/Solana. Smart contracts design, implementation, and testing (using typescript). Project successfully works on the market and ranks in the top 100 of Coinmarketcap. <br />- `2022-2023`: Development of Domain name service using Rust on Elrond blockchain. Smart contracts / Backend/deployment. | andriyslisarchuk@gmail.com |

**Comment by franklywatson** [comment]
This proposal has been accepted and approved. Look forward to working with you @Guitarheroua

**Comment by franklywatson** [comment]
Confirming the completion/merging of the fixes for the following 3 tasks so far. Thanks for the great work @Guitarheroua!! Keep it up and look forward to wrapping up this milestone! 

- [X] https://github.com/onflow/flow-go/issues/3040
- [X] https://github.com/onflow/flow-go/issues/2906
- [X] https://github.com/onflow/flow-go/issues/3133
