### ISSUE TITLE
TypeScript support for FCL

### ISSUE THREAD

**Issue by louisguitton** [onflow/developer-grants#18]
# TypeScript support for FCL

# Grant category
Developer service

# Description

## Problem statement

- Target audience: every dApp developer who uses FCL but has a TypeScript codebase. Although it's not clear whether TypeScript is more popular than JavaScript, it is clear that TypeScript is the next JS flavour to support.

In the "State of Javascript 2021" report: Asked about their use of “JavaScript flavours,” 69% of survey respondents now use TypeScript, compared to just 21% six years ago. JavaScript flavours were defined as languages that compile to JavaScript. Other JavaScript flavours trailed TypeScript by a large margin; the next was Elm at 2.4%, followed by Flow at 1.7% and CoffeeScript at 1.5%.

Ref: https://2021.stateofjs.com/en-US/other-tools/#javascript_flavors
<img width="1245" alt="image" src="https://user-images.githubusercontent.com/7823843/168012036-29870ec2-33b9-439b-b003-b48a022acd67.png">

- Evidence for the need:
    - traction for my PR in https://github.com/louisguitton/DefinitelyTyped/pull/1
    - message from FCL dev team in https://github.com/onflow/fcl-js/pull/924
    > Our current plan for TS type support will be [here](https://github.com/louisguitton/DefinitelyTyped/pull/1). Post 1.0 we will re-evaluate adding type files to the official release.

## Proposed solution

- Based on https://github.com/louisguitton/DefinitelyTyped/pull/1  and the feedback from the developer community, open a PR against https://github.com/onflow/fcl-js with one `.d.ts` file per package in the `packages/` directory. 
- During a "call for proposal" period of ~2 weeks, synthesise other efforts that have surfaced during the process (e.g. [@samatech/onflow-fcl-esm package](https://github.com/samatechtw/onflow-fcl-esm) or other homegrown solutions in private repos)
- Include JSDoc documentation in the declaration files.
- Include a JSDoc to Markdown solution to make sure [`api.md`](https://github.com/onflow/fcl-js/blob/master/docs/reference/api.md) is in sync with the code

## Impact

- In what ways does this benefit the broader Flow developer ecosystem?

1. If @onflow/fcl supports TS officially, this will speed up FCL (and hence Flow) adoption for modern teams. The benefit will be faster dApp innovation (e.g. DeFi, NFT marketplaces, etc...)
2. DevX (developer experience) will be greatly improved as the types also contain JSDoc that matches 1:1 the docs website.

# Milestones and funding

Total: 40000 USD

| Milestone | Deliverables   | Timeline | Risks                   | USD requested |
| --------- | -------------- | -------- | ----------------------- | -------------- |
| 1 - FCL declaration types  | Add TS declaration files to FCL repo in individual components with approval from FCL team. | 2 months |   | 20000 USD        |
| 2 - FCL JSDoc documentation  | Add new comments, definitions, and examples to the FCL public facing API. Intellisense should work with the documentation on VS Code. | with milestone 1 |  | 10000 USD        |
| 3 - Automated FCL API documentation | Generate `docs/reference/api.md` programatically from the JSDoc documentation using an off-the-shelf solution like https://github.com/jsdoc2md/jsdoc-to-markdown | 1 month | No off-the-shelf solution does what the fcl-js codebase needs | 10000 USD        |

# Team

| Name | Role                | Bio | Contact         |
| ---- | ------------------- | --- | --------------- |
| Louis Guitton | Main contributor | VP Eng at OneFootball Labs; laguitte.find; worked in ML + data for 6 years before building dApps since Nov 2021 | louisguitton93@gmail.com |
| Yann Uzel | Senior reviewer | CTO & Co-Founder @ MFL; Full-Stack Developer & Passionate Builder | [Luze26](https://github.com/Luze26) |
| Pier'Antonio PICHIERRI  | Reviewer | MFL Blockchain and Fullstack Developer | [ppichier](https://github.com/ppichier)
| Antoine ALEJANDRO | Reviewer | MFL Co-Founder and Fullstack developer | [antoinealej](https://github.com/antoinealej)
| Charles Ouverleaux | Reviewer | OneFootball Web developer | [CharlesOuverleaux](https://github.com/CharlesOuverleaux)

# Milestone completion
- [ ] FCL declaration types
- [ ] FCL JSDoc documentation
- [ ] Automated FCL API documentation

**Comment by Luze26** [comment]
Would be really nice to TypeScript support :+1: . Lot of teams create their own types which are always imperfect and not the best developer experience.

**Comment by CharlesOuverleaux** [comment]
This will allow new projects to speed up and improve development on Flow (prevention type bugs & IntelliSense recos)!

**Comment by srinjoyc** [comment]
Hi @louisguitton,

Thanks for this application! The FCL team is very excited to welcome the contribution and will help making sure it gets merged in. There is just two things of note that may modify the scope of this grant:
1. We love the idea of having JSDoc generate the api.md - the only small request here was to ensure that complex types in the JSDoc are imported in rather than defined, similar to this [post](https://stackoverflow.com/questions/49836644/how-to-import-a-typedef-from-one-file-to-another-in-jsdoc-using-node-js ).
2. Flag for the future: FCL will eventually pursue a fully typed codebase at which point we'd generate the types file but this likely will not happen in the next 3-6 months and hopefully your contribution will help us move in that direction piece by piece. Until then, we're happy to schedule a weekly or bi-weekly call with the FCL team to help push this through.

Lastly, as an action item, would you be able to edit your requested FLOW amounts in USD instead? If you prefer, you can also leave it blank and we can provide suggested amounts. We are going through a small process change and believe it'll be much easier to discuss in terms of USD although the payout will be in FLOW based on a 30-day average token price.

If you're good with all this, leave a reply and we can move forward in the process!

**Comment by louisguitton** [comment]
hi @srinjoyc thanks for the reply and sorry for the slow response.
Point 1 and 2 are awesome.

> Lastly, as an action item, would you be able to edit your requested FLOW amounts in USD instead? If you prefer, you can also leave it blank and we can provide suggested amounts. 

Change of process makes sense given the market conditions lately I guess. I have gone ahead and applied a 3USD = 1 FLOW ratio. Feel free to still suggest amounts either here or in Discord PMs, I'm really open there. One thing that's close to my heart is that I want this to be a team effort, so I am involving a few reviewers.

**Comment by srinjoyc** [comment]
Thanks! Responded via discord to set up a quick chat to further discuss scope, effort, timeline, etc.

**Comment by srinjoyc** [comment]
Suggested:

| Milestone                   | Deliverables                                                                                                                                                                            | Suggested Deadline | USD Suggested |   |
|-----------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|--------------------|---------------|---|
| 1 - FCL declaration types   | Add TS decleration file to FCL repo with approval from FCL team and merge in DefintelyTyped PR.                                                                                         | July 30th, 2022    | 20,000         |   |
| 2 - FCL JSDoc documentation | Add new comments, definitions, and examples to the FCL public facing API. Generate documentation from TS definitions in MD. Intellisense should work with the documentation on VS Code. | August 15, 2022    | 10,000         |   |

**Comment by louisguitton** [comment]
@srinjoyc thanks for the comment and the time today.
As agreed in the call, I have now updated this issue with the agreed milestones, and I have added the third milestone about docs generation. I have updated the grant amount according to your suggestion.

**Comment by srinjoyc** [comment]
@louisguitton great - updated my recommendation as well. Moving to your email for finalizing the paperwork!

**Comment by srinjoyc** [comment]
This grant has been accepted, pending final approval 🎉

**Comment by louisguitton** [comment]
@srinjoyc agreement has been signed by all parties. I have started the work in https://github.com/onflow/fcl-js/pull/1305

As agreed with @JeffreyDoyle and @gregsantos, I will split the types and tests package per package.
This should make it easier for reviewers as they can browse/review commit per commit.

**Comment by maggo** [comment]
Great to see this being accepted! I've been longing for types in FCL since I started working with it 😁

My plans for https://github.com/maggo/use-flow include full typing as well so I'm looking forward to integrate your work and give feedback!

**Comment by adbario** [comment]
Great work all; type definitions will hugely improve the dev experience 🚀 

I've just added definitions for [@onflow/flow-js-testing](https://github.com/onflow/flow-js-testing) API functions to [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped), and they can be installed with:

```shell
npm i --save-dev @types/onflow__flow-js-testing
```

https://www.npmjs.com/package/@types/onflow__flow-js-testing

**Comment by gregsantos** [comment]
Hey @louisguitton! Is there any progress expected here soon? Any help we can offer?

**Comment by louisguitton** [comment]
> Hey @louisguitton! Is there any progress expected here soon? Any help we can offer?

Hi @gregsantos @srinjoyc, sadly no progress to report. The last 2 months have been very busy with the launch of http://aera.onefootball.com/ (drops, marketplace, challenges). My work has left me with no evenings or weekends to work on OSS as my priority shifted to (try) make Aera a success. This is as selfish as it gets, but I had to prioritise my own health and my employer's project over delivering this body of work.

My plan is to use the next 2 weeks to re-assess the existing plan for this issue and propose an adjusted timeline.
I am still hooked on the technical challenge behind this grant.

Let me know your thoughts.

**Comment by gregsantos** [comment]
Thanks for your reply @louisguitton. We see you out there hustling!
Appreciate you getting back to this much requested grant. Keep us looped in here and let me know if you need anything

**Comment by gregsantos** [comment]
Following up here @louisguitton re: any updates or adjusted timeline. Happy to arrange a chat if that's easier for you!

**Comment by louisguitton** [comment]
Hey everyone. 
Sorry for this radio silence. The last few months have been packed and resulted in me leaving my role at OneFootball.
Although I would now have time to continue the work for this grant, I no longer am interested in pursuing this opportunity.
What is the process to "handover" or "close" a grant?
Best

**Comment by alxflw** [comment]
Thanks for the update @louisguitton. Sad to hear of course! We will close this issue to reflect this change. @gregsantos @chrisackermann - let's review if we should open an RFP instead
