### ISSUE TITLE
Flowser: Integrate it into the Flow CLI and develop Flowser desktop app

### ISSUE THREAD

**Issue by monikaxh** [onflow/developer-grants#27]
# Flowser: Integrate it into the Flow CLI and develop Flowser desktop app

# Grant category

OpenSource maintenance

# Description

Create a standalone Flowser application that can be simply installed and also launched within the Flow CLI.

## Problem statement

Even though a Flowser was built to be easy to use and developer-friendly the installation process requires multiple steps and tools to be pre-installed which in the end hurts the UX. We want to make Flowser as accessible as possible and part of that would be to wrap it up in a standalone application that doesn’t require other dependencies and it works with a single click. The wish for this improvement was also confirmed by our community on GitHub as seen here: https://github.com/onflowser/flowser/discussions

Currently, in order to install the Flowser you need to pre-install:

- NodeJS environment
- Postgres database
- Docker

Besides the technical difficulties, the current version comes with a cost of higher CPU and memory usage as well as isolation of the Flow CLI which is contained in a docker instead of using the one user has already installed on their system.

## Proposed solution

Our proposed solution consists of multiple steps. First, we would have to make sure Flowser is updated with the latest versions of the CLI and Emulator, then we would work on removing the dependencies mentioned above. Postgres database would be swapped with in-memory storage that would have an abstract API and hideaway technicalities of data persistence. Since the Flowser application would be launched by the CLI after we complete all the changes we can remove the CLI as a dependency too and use the one that launched the Flowser in the first place. We would follow by making sure the Flowser can be launched in a platform-independent which would allow us to wrap it in an Electron environment. Electron is a framework for creating native applications from web applications. Last but not least all of the above-mentioned actions would be accompanied by changes in the UI design, improvements in the UX, and support for any new UI components.

## Impact

- The user experience would be much more convenient and pleasant when working with the graphical user interface.
- Flowser would be more accessible to more developers.
- Flowser UX (UI, ease of use, execution time, resource usage,..) would be significantly improved
- Support of the newest CLI versions would enable new functionalities in Flowser and give us unlimited possibilities for developing new features in the future.

# Milestones and funding

Milestone | Deliverables | Timeline | Risks | FLOW requested
-- | -- | -- | -- | --
1 - Database migration | Migration to a platform-independent SQL database interface. Solve a few related issues along the way, such as <a href="https://github.com/onflowser/flowser/issues/13">data persistence issues</a> and the lack of <a href="https://github.com/onflowser/flowser/issues/6">error recovery mechanism</a>. | 2 weeks | - | 1200
2 - Flowser architecture changes | Platform independent architecture to support Electron (or any other) environment. | 1 week | - | 600
3 - Migration to the newest version of flow-cli and emulator | With the migration to the newest version of flow-cli we will support the newly added flow-cli functionalities and we will integrate Snapshot management into Flowser. | 3 weeks | - | 1800
4 - Desktop app | Standalone application with electron support. | ~ 1 month | - | 3000
5 - Maintenance, support & PR | We will ensure maintenance and support for emulator and flow-cli updates. Public release and marketing will be done together with engaging our community on all of our channels: Twitter, Discord, and blog post. | 3 months | - | 3000
New design and GUI improvements | The current design of the Flowser tool needs to be modified and redesigned for a standalone application and for smaller window sizes as well. An additional new design needs to be created, to support all the new functionalities, that will be available in the Flowser desktop app. We will also improve the GUI with a <a href="https://github.com/onflowser/flowser/discussions/82">SubNavigation redesign</a>. We will include global statistics on the left side of the search component, to give the user more information. These deliverables will be ongoing during milestones 1-3. This is how will we ensure, that the design will be ready for the start of milestone 4. | ~ 1 month | - | 3000

# Team

Github | Name | Role | Bio | E-mail
-- | -- | -- | -- | --
@bartolomej | Bartolomej Kozorog | Full stack developer | Passionate developer and CS student. Currently building Flowser and part-time working at various tech companies. | bartolomej.kozorog@gmail.com
@monikaxh | Monika Hriberšek | UX/UI Design + Graphic design | Proprietor @ Monikart; UX/UI Designer @ Flowser since Sep 2021; Designing: mobile apps, websites, social media content, NFTs. Additional experience: Product Manager @ Renault&Nissan Financing (~ 4y). | monika.hribersek@gmail.com
@jakic12 | Jakob Drusany | Full stack developer | Computer science and maths student. Developing Flowser and many other personal projects. | drusany.jakob@gmail.com

# Milestone completion
- [x] Database migration
- [x] Flowser architecture changes
- [x] Migration to the newest version of flow-cli and emulator
- [x] New design and GUI improvements
- [x] Desktop app
- [x] Adoption
- [x] Maintenance, support

**Comment by srinjoyc** [comment]
Hi Flowser Team,

We're sorry for the delay in the response here. We're eager to review and get going on your proposal but waiting on a few engineers to return so we can have a proper look. We will try and get back to you by the end of next week if not earlier. We appreciate your patience!

**Comment by monikaxh** [comment]
Thank you for the update, @srinjoyc! 

We understand the situation and we are happy to wait for your feedback on our proposal.

**Comment by srinjoyc** [comment]
Hello Flowser team,

We've updated a few milestones and moved to suggested USD amounts, but overall your proposal looks good. Here is what we would recommend: 

| Milestone                                                    | Deliverables                                                                                                                                                          | Suggested Deadline | USD Suggested |   |
|--------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------|--------------------|---------------|---|
| 1 - Database migration                                       | Migration to a platform-independent SQL database interface.                                                                                                           | July 30th, 2022    | 5,000         |   |
| 2 - Flowser architecture changes                             | Platform independent architecture to support Electron (or any other) environment.                                                                                     | August 15, 2022    | 2,500         |   |
| 3 - Migration to the newest version of flow-cli and emulator | With the migration to the newest version of flow-cli we will support the newly added flow-cli functionalities and we will integrate Snapshot management into Flowser. | August 30, 2022    | 7,500         |   |
| 4 - New design and GUI improvements                          | Flowser desktop app design and optimization. Improve the default GUI to support new features and architecture. Design global statistics for users.                    | August 30, 2022    | 10,000        |   |
| 5 - Desktop app                                              | Standalone desktop application (macOS and Windows) with electron support.                                                                                             | September 15, 2022 | 10,000        |   |
| 6 - Adoption                                                 | Get at least 100+ unique downloads on the new version of Flowser (any environment).                                                                                   | December 30, 2022  | 5,000         |   |
| 7 - Maintenance, support & PR                                | Provide on-going maintainenece and support as needed to reach adoption milestone.                                                                                     | December 30, 2022  | 10,000        |   |


**Total suggested USD amount: $50,000**
Let us know if you're good with this table and we can start the approval process on our end!

**Comment by srinjoyc** [comment]
@monikaxh - sent over an email to finalize some paperwork!

**Comment by srinjoyc** [comment]
This grant has been accepted, pending final approval 🎉

**Comment by monikaxh** [comment]
The first milestone completed 💪
https://github.com/onflowser/flowser/pull/88
