### ISSUE TITLE
Developer Onboarding Guides

### ISSUE THREAD

**Issue by CapnMB** [onflow/developer-grants#28]
# Developer Onboarding Guides

# Grant category
Educational material

# Description

## Problem statement
Flow needs more developers - so onboarding new devs into the ecosystem is a priority. While there are over [18,000+ active monthly web3 developers](https://medium.com/electric-capital/electric-capital-developer-report-2021-f37874efea6d) (as of Jan 2022), **less than 200 developers work in Flow/Cadence** (compared to over _4000_ in Ethereum/Solidity/Vyper). And while nearly 35,000 new developers joined or learned web3 in 2021, the number joining Ethereum was vastly larger (20-25% of all new devs) than any other ecosystem, including Flow.

In order for Flow to continue its growth, it needs to tap into the existing web3 devs that only know Ethereum/Solidity.

However, there are a couple problems with onboarding these developers:

- While new web3 developers are entering the space quickly (numbers nearly doubled from 2021 to 2022) most are introduced to web3 through Ethereum/Solidity - and stay there. Smart contract development is difficult, with a long learning curve, and devs are not incentivized to learn a new paradigm/chain/language.
- For current Ethereum devs, even if they are interested in the Flow ecosystem, learning Flow/Cadence requires a paradigm shift (resource-oriented vs object-oriented) which makes onboarding difficult. This is a serious barrier to entry.  

The ecosystem needs more paths for Ethereum developers to enter Flow.

## Proposed solution
We want to bring more devs to Flow by creating a series of technical guides that lead developers through the shift from their current stack to Flow. Our group, [Dev Spotlight](https://www.devspotlight.com/), is highly qualified to create these guides as we have deep experience both in technical content creation (including web3) and in similar projects for other ecosystems.

### Series Details
We will create the following series: 

- **Ethereum to Flow Guide** - The first series will consist of 5 articles that guide current Ethereum devs through the process of learning Flow/Cadence, and how it is different (and similar) to Ethereum/Solidity. It will demonstrate a clear and straightforward path to making the transition and showcase the benefits of moving to Flow.

This series will be technically detailed and informative, taking the reader from _0 to 100 Building on Flow_. The series will include diagrams, screen shots, sample code, etc. The series can be published on Flow properties and also syndicated to the 3rd party sites dev.to, DZone, Medium, Hacker Noon, and Hashnode. 

We can produce these articles independently without any work from the Flow team (we have a strong internal team of developers, writers, technical editors, code reviewers, and copy editors that work together to create a final draft of high quality) but we can also work closely with the Flow team to focus the articles on areas of interest. Both series will be available for review by the Flow team before publishing.

### Qualifications
We have a proven track record of creating readable and digestible technical content around difficult topics. We have created many similar series that take developers from beginner to expert in different areas. We are experienced in web3 (our web3 client base is private but includes many top protocols and companies). Our web2 clients include some of the top developer-focused companies in the world such as Twilio, Salesforce, MongoDB, Cisco, and many more. While much of our work is ghostwritten and private, we are happy to provide examples to the Flow team upon request.

Over the past five years we have published over a thousand high-quality technical articles that have been read by tens of millions of developers. We are some of the most popular and followed writers on the above-mentioned 3rd party sites (such as DZone and dev.to) and can reach an audience that has not yet been introduced to Flow. We know this audience well and we know how to create successful technical content.

## Impact

This series of technical guides will introduce a straightforward path to learning Flow/Cadence for Ethereum devs. This content should increase the number of developers in the ecosystem. 

At the end of the project, we will publish a metrics report capturing the number of syndicated views and interactions. Please note that click-throughs/conversions will need to be measured by the Flow team as we don’t have access to this information.

# Milestones and funding

A total of five articles for a total of 5,380 Flow (plus bonus based on # of views), published over two months.

<html>
<body>
<b style="font-weight:normal;" id="docs-internal-guid-73ada314-7fff-c138-a902-dcae46787582"><p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:12pt;font-family:Arial;color:#24292f;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Ethereum to Flow Guide</span></p><br /><div dir="ltr" style="margin-left:0pt;" align="left">

Milestone | Est Publication Date | Cost
-- | -- | --
Article 1 - Side by side examples. Create the same smart contract in Solidity and Cadence, comparing and contrasting. | 4 weeks from start | 2700 USD
Article 2 - Why move to Flow + Cadence. Similarities and differences to Ethereum (Flow more scalable/multi-node arch, cheaper, SPoCKs, etc. beta smart contracts). Differences in philosophy of the chains. Resource oriented vs OO. Can port. NFTs. Gaming. DeFi. | 5 weeks from start | 2700 USD
Article 3 - Tools and libraries for Flow. FCL, CLI, VS Code Extension, Go SDK, etc. (again, comparing and contrasting to Solidity tools to help) | 6 weeks from start | 2700 USD
Article 4 - A full sample project with code (again, always contrasting to Solidity). | 7 weeks from start | 2700 USD
Article 5 - Best practices, patterns and anti-patterns. Where to go next. | 8 weeks from start | 2700 USD
Cumulative Total of 50,000 views | n/a | 3750 USD 
Cumulative Total of 100,000 views | n/a | 5000 USD

</div><br /></b>
</body>
</html>

# Team
<html>
<body>
<b style="font-weight:normal;" id="docs-internal-guid-01517435-7fff-fca8-8a02-e8e9d95a1878"><div dir="ltr" style="margin-left:0pt;" align="left">

Name | Role | Bio | Contact
-- | -- | -- | --
Michael Bogan | Project Co-Lead | Founder. 25+ years of development and systems architecture experience. | michael@devspotlight.com
Paulie McAviney | Project Co-Lead | Web3 lead. Core member of dev_dao. | paulie@devspotlight.com
Alvin Lee | Senior Editor | 20+ years of development and technical editing. | alvin@devspotlight.om
Various | Writers | We have a core group of ~10 web3 writers who will all contribute to the content. |  

</div><br /><br /></b>
</body>
</html>

# Milestone completion
- [x] Article 1 - Side by side examples
- [ ] Article 2 - Why move to Flow + Cadence
- [ ] Article 3 - Tools and libraries for Flow
- [ ] Article 4 - A full sample project with code
- [ ] Article 5 - Best practices, patterns and anti-patterns
- [ ] Cumulative Total of 50,000 views
- [ ] Cumulative Total of 100,000 views

**Comment by alxflw** [comment]
thanks for the submission @CapnMB! would you be open to the following changes? 

1) Remove Series 2 for now. We could always explore another grant for another series in the future
2) Change the order of Series 1 pieces to: 2, 1, 3, 4, 5
3) Add an adoption milestone based on the cumulative views of all articles

**Comment by CapnMB** [comment]
@alxflw - sure! Updates done.

**Comment by CapnMB** [comment]
Hi @alxflw - it was kind of in there already, but I made it more clear. The content will be published to dev.to, DZone, Medium, Hacker Noon, and Hashnode. The original will be on dev.to, with the rest being canonical links.

**Comment by alxflw** [comment]
hi @CapnMB, we just accepted this grant proposal 🚀 

 I'll reach out to you directly with the next steps!
