### ISSUE TITLE
Fiat - NFT payment plugin for wallets

### ISSUE THREAD

**Issue by wfalcon0x** [onflow/developer-grants#48]
# Walletless

# Grant category
Developer tools / services

# Description
Fiat-NFT payment plugin for FLOW wallets

## Problem statement
- Accepting direct card payments for NFTs requires significant dev work
- Currently, FLOW wallets require you to buy crypto first, then buy the NFT, paying twice the fees and taking double the time

### Target audience
- Wallets on FLOW wanting to offer direct card NFT checkouts for their users

### Evidence for the need
- Direct card-to-NFT purchases boosts sales by 300% (MoonPay survey)
- Discussions with software engineers building wallets and infrastructure on FLOW

## Proposed solution
- Fiat-NFT payment solution that plugs into wallets on FLOW

## Impact
- Higher sales conversions for FLOW projects
- Improved Wallet user experience

### In what ways does this benefit the broader Flow developer ecosystem?
- Save months of dev work 
- Handle FIAT payments for wallet providers
- Handle fraudulent activities and offer chargeback guarantee

# Milestones and funding

> Note: You can leave the USD proposal empty / "TBD". Please consider adoption and/or maintenance milestones at the end of your project.

| Milestone | Deliverables   | Timeline | Risks                   | USD proposal |
| --------- | -------------- | -------- | ----------------------- | -------------- |
| 1 - Purchase Transaction Validator | API to determine payable amount based on transactions | 3 weeks | - | |
| 2 - Collect Eligible Transactions | Collect set of eligible transactions from marketplaces and community  | 1 week | - | |
| 3 - Opensource Core Functionality | Opensource the core functionalities of the purchase transaction validator  | 1 week | - | |
| 4 - Developer Typescript SDK | - Typescript SDK for card payment for NFTs<br> - SDK documentation   | 4 weeks |  |  |
| 5 - Developer Android SDK | - Android SDK for card payment for NFTs<br> - SDK documentation   | 4 weeks |  |  |
| 6 - Testing | - Testing and bug fixing  | 2 weeks |  |  |
| 7 - Example Integration   | Integrate test plugin solution into the chrome extension wallet | 0.5 week  | - | |
| 8 - Adoption | 1 wallet integrates the fiat payment<br> - Gather feedback   | 1 week |  |  |
| 9 - Maintenance | Supporting wallet providers, resolving issues   | 4 months |  |  |

# Team

| Name | Role                | Bio | Contact         |
| ---- | ------------------- | --- | --------------- |
| Daniel N| Product | Oxford University Engineering scholar, Ex-BAML, experience in tech and finance | daniel@eucleides.com |
| Akos E| Architect and Full Stack | Engineer graduating in Germany, years in software development, technical leadership and architecture | akos@eucleides.com |
| Mislav K | Front-end Engineer | Front-end experience for many start-ups, including web3 |  |
| Paul F| Business Analyst | Accountant, ex-Deloitte, c-suite experience, background in finance and healthcare |  |

# Milestone completion
- [x] Purchase Transaction Validator
- [x] Collect Eligible Transactions
- [ ] Opensource Core Functionality
- [ ] Developer SDKs
- [ ] Testing and example integration
- [ ] Adoption
- [ ] Maintenance

**Comment by bjartek** [comment]
In the spirit of transparancy can we update the grants to contain the rewards?
