### ISSUE TITLE
Interactive Art NFT

### ISSUE THREAD

**Issue by alxflw** [onflow/developer-grants#7]
`chana.find | iaNFT#7569` is working towards an implementation and standard for "Interactive Art NFTs on Flow"

Repo: https://github.com/hichana/iaNFT-Flow

# Milestone completion
- [x] Define MVP
- [ ] Interactive NFT standard definition, generic tools, and “How-to” supporting materials 
- [ ] No-code app demonstrating iaNFTs launched to mainnet
- [ ] Launch with 3rd party partner

**Comment by Aliserag** [comment]
Given the time since this has been submitted I'm closing this down, please reach out to me if you'd like to share what you're working on now and explore potential opportunities [ali.serag@flowfoundation.org](mailto:ali.serag@flowfoundation.org).
